export const topics=[
    {
      id: 1,
      title: "How to calculate TDD for a variable load?",
      author: "John Engineer",
      avatar: "https://au6r55axt30njf9e1.lite.vusercontent.net/placeholder.svg?height=40&width=40",
      replies: 12,
      views: 234,
      category: "Calculations",
      lastActivity: "2 hours ago",
    },
    {
      id: 2,
      title: "Best practices for harmonic mitigation in textile industry",
      author: "Sarah Consultant",
      avatar: "/placeholder.svg?height=40&width=40",
      replies: 8,
      views: 156,
      category: "Industry Specific",
      lastActivity: "1 day ago",
    },
    {
      id: 3,
      title: "PSERC penalties - recent case discussion",
      author: "Regulatory Expert",
      avatar: "/placeholder.svg?height=40&width=40",
      replies: 24,
      views: 412,
      category: "Regulations",
      lastActivity: "3 days ago",
    },
    {
      id: 4,
      title: "Active vs Passive filters - ROI comparison",
      author: "Cost Analyst",
      avatar: "/placeholder.svg?height=40&width=40",
      replies: 15,
      views: 267,
      category: "Mitigation",
      lastActivity: "5 days ago",
    },
    {
      id: 5,
      title: "Short circuit calculation methods - IEEE vs IEC",
      author: "Technical Student",
      avatar: "/placeholder.svg?height=40&width=40",
      replies: 7,
      views: 189,
      category: "Calculations",
      lastActivity: "1 week ago",
    },
  ];

  